### ISSUE TITLE
Improve exception messages

### ISSUE THREAD

**Issue by fuetgeo** [remondis-it/remap#107]
Great work!
Two messages that made it hard to pinpoint the cause:

When a mapper is missing it would be nice to mention the property name for which this is needed:
```No mapper found for type mapping from java.lang.Float to java.lang.Double```

When the same mapper is accidentally assigned twice by calling ```mapping.useMapper(mapper)```:
```A mapper mapping the type A to type B was already registered.```
(with A and B being the types of the mapping, not of the mapper, which was additionally confusing for me)

**Comment by schuettec** [comment]
Hey, I totally agree with this, but
> When a mapper is missing it would be nice to mention the property name

the property name would be difficult, because a mapper is not only responsible for one property. There can be multiple properties that are mapped by the mapper that is missing.

Are you interested in making a contribution? ;)

**Comment by schuettec** [comment]
Haha yah and this
> When the same mapper is accidentally assigned twice by calling mapping.useMapper(mapper):
A mapper mapping the type A to type B was already registered.

is a bug :D

I will fix that immediately.

**Comment by schuettec** [comment]
FYI #108 for the bug.

**Comment by schuettec** [comment]
#109 Implements the message with property name hints if a mapper is missing. Wold look like this:
```
com.remondis.remap.MappingException: No mapper found for type mapping from java.lang.CharSequence to java.lang.String.
For example used by the property mapping from Property 'forename' in A to Property 'forename' in AResource.
```

Is this what you would expect to see?

**Comment by fuetgeo** [comment]
Thanks, exactly as expected. Awesome!
