### ISSUE TITLE
Mapping is not applied for Set properties

### ISSUE THREAD

**Issue by fuetgeo** [remondis-it/remap#110]
If a property of type `Set<A>` needs to be mapped to a property of type `List<B>`, a mapping from A to B is demanded, but not applied. Elements will be copied 1:1, which means you'll end up with A instances in the destination `List<B>`

**Comment by schuettec** [comment]
Oh, I can reproduce this. ReMap currently supports nested collections, but the assumption is that the nesting is equal on both sides. But unfortunately this is not validated.

At the moment I don't know if ReMap could analyze the collection types.

I will have a look...

**Comment by schuettec** [comment]
I build a fix in #111 so that ReMap now analyzes the destination collection types. This was a little more complicated because due to the fact that ReMap supports nested collections, the nested destination types have to be traversed.

Would you like to support us with testing the solution in your use-case? You may compile the solution locally to test the target version 4.1.16.

**Comment by fuetgeo** [comment]
Successfully tested - works great. Thanks for the quick fix!

Just realized that my description was not on spot, but you did exactly the right thing.
I had `.useMapper(TypeMapping.from(Set.class).to(List.class).applying(ArrayList::new))` applied, which expains my weird result.

**Comment by schuettec** [comment]
Hey, good to hear. 
Yeah you really stirred up a hornets' nest with that bug report :D Thanks for that 👍 
It's documented that ReMap currently cannot handle maps, but the whole implementation of nested generic types was wrong, so the mapping of nested sets went bananas like you mentioned.

A tough nut to crack, but if I'm able to finish #112 nested maps/collections will be fully supported, ...I hope :)

**Comment by schuettec** [comment]
`4.1.16` is on its way to Maven Central^^
