### ISSUE TITLE
Is it possible to update an existing object instead of creating a new one?

### ISSUE THREAD

**Issue by sebasira** [remondis-it/remap#133]
I'm implementing **reMap** in every Entity <-> DTO conversion. I also use a DTO when updating an Entity, and thus I would expect to **read** the original Entity from the DB and update the values when mapping.

Let me show you a dummy example:

```java
public class User {
   private String name;
   private String lastname;
   private Integer age;
}

public class User_updateDTO {
   private String name;
   private String lastname;
   private Integer age;
}
```

What I would normally do is (without reMap):

```java
User existingUser = readUserDB();
if (null != dto.getName()){
    existingUser.setName(dto.getName());
}
// ... and the same for the other attributes
```

I was thinking in something like this:

```java
Mapper< User_updateDTO, User > mapper = Mapping.from(User_updateDTO.class)
                .to(User.class)
                .replace(User_updateDTO::getName, User::getName)
                    .withSkipWhenNull(value -> value)
                .replace(User_updateDTO::getLastname, User::getLastname)
                    .withSkipWhenNull(value -> value)
                .replace(User_updateDTO::getAge, User:: getAge)
                    .withSkipWhenNull(value -> value)
                .mapper;
```

The problem of course is the mapper creates a new User instance.

Maybe you could guide me in other direction in order to use reMap when updating. I appreciate any guidance. How do you work with updates? My idea of the DTO is to restrict the attributes allowed for update

**Comment by schuettec** [comment]
Hi,
you can actually suppress the creation of new instances using `Mapper.map(source, destination)`. With this method you are able to specify an instance as `destination`, which would be the instance from database in your example. This way ReMap overrides all fields that are affected by your mapping declaration.
So I'm pretty sure you can build a mapper for updating :)

**Comment by sebasira** [comment]
Thanks! I'll give it a try and let you know!

**Comment by schuettec** [comment]
You're welcome. Yah please let me know :)

**Comment by sebasira** [comment]
It worked like a charm! Thank you again!

For anyone else interested in this, I will write down how I'm using it. Starting from the example in the issue description:

```java
User existingUser = readUserDB();
mapper.map(dto, existingUser);
```

Where **dto** is an instance of `User_updateDTO` with the updated data.
