### ISSUE TITLE
custom mapping 

### ISSUE THREAD

**Issue by Roddys** [remondis-it/remap#136]
Is it possible to add custom mapping logic on object level not just on the fieldlevel, like in 'replace'?

Here is an example of my use case, where I can see no way to solve it with remap:

class From{
Location mainLocation;
List<Location> allMyLocations;
}

class Location{
String locationName
}
-----------------------
class To{
List<LocationResource> allMyLocations;
}

class LocationResource{
String locationName;
Boolean isMainLocation;
}

Cheers!
Sebastian

**Comment by schuettec** [comment]
Hi, the following works

```
    Mapper<Location, LocationResource> locationMapper = Mapping.from(Location.class)
        .to(LocationResource.class)
        .set(LocationResource::isMainLocation)
        .with(false)
        .mapper();

    Mapper<From, To> mapper = Mapping.from(From.class)
        .to(To.class)
        .omitOtherSourceProperties()
        .set(To::getAllMyLocations)
        .with(from -> {
          List<LocationResource> locations = locationMapper.map(from.getAllMyLocations());
          locations.stream()
              .filter(loc -> isMainLocation(from, loc))
              .forEach(loc -> loc.setMainLocation(true));
          return locations;
        })
        .mapper();
```

I know this can get a little bit unhandy if the type hierarchy is larger than it is in this example. But you can solve this type of mappings with a set-operation.
