### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by chkpnt** [remondis-it/remap#138]
I'm getting the following warning when using `remap` with Java 11:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/Users/ich/.gradle/caches/modules-2/files-2.1/cglib/cglib/3.2.9/a4b7af2ea0a5ecad2d283c2fff119009f0c60d20/cglib-3.2.9.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

What is the recommended way to suppress this warning?

**Comment by schuettec** [comment]
Hi,
this occurs on Java version >= 9. If you created a module you can fix this
by declaring your module as 'open module' in module-info. This way you
allow reflective access in a Java >= 9 compatible way.




Gregor Dschung <notifications@github.com> schrieb am Mi., 18. Nov. 2020,
11:50:

**Comment by chkpnt** [comment]
Thanks for the quick response, which gave me the correct hint (towards the module system). Credits also to @nipafx, whose [blog post](https://nipafx.dev/java-11-migration-guide#illegal-access-to-internal-apis) gave me further insights.

At the moment I do not want to migrate to the JPMS , so I'm now using the `--add-opens` argument for the JVM, i.e. the following for Gradle: 

```groovy
application {
    applicationDefaultJvmArgs = ["--add-opens", "java.base/java.lang=ALL-UNNAMED"]
}
```

**Comment by nipafx** [comment]
Glad to hear, the blog post helped, @chkpnt! 

Huh, I didn't know Remondis had an IT branch - talk about garbage collection... 😂 Sorry for the silly pun, I couldn't resist.

**Comment by schuettec** [comment]
Haha yes, default joke for new employees ;)
