### ISSUE TITLE
Java 17 compatibility 

### ISSUE THREAD

**Issue by nacron** [remondis-it/remap#146]
Hello Remondis Team,

we are using your mapper and are very happy with it.
Now we wanted to upgrade to Java 17 and found out that the underlying library cglib (https://github.com/cglib/cglib) no longer supports Java 17. They have this paragraph on their github page:

_IMPORTANT NOTE: cglib is unmaintained and does not work well (or possibly at all?) in newer JDKs, particularly JDK17+. If you need to support newer JDKs, we will accept well-tested well-thought-out patches... but you'll probably have better luck migrating to something like [ByteBuddy](https://bytebuddy.net/)._

Are there any plans to move the underlying library to something like byte buddy?

Cheers
Benedikt

**Comment by schuettec** [comment]
Thanks for feedback. We will migrate to Byte Buddy soon.
