### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by eideckerh** [remondis-it/remap#33]
List of possible API Improvements. They are collected in this Issue, because they are breaking changes and should be implemented together in a single release. 

- Methods `com.remondis.remap.ReplaceCollectionAssertBuilder.andTest(Transform<RS, RD>)` and  `com.remondis.remap.ReplaceAssertBuilder.andTest(Transform<RS, RD>)` should be renamed so that the method name indicates that the test is performed against<code>null</code> input.

**Comment by schuettec** [comment]
This change would generate a great deal of migration effort and the documentation now reflects that.
