### ISSUE TITLE
Possible bug on Boolean field ?

### ISSUE THREAD

**Issue by mmaryo** [remondis-it/remap#35]
Hello 

ReMap throw always exception on Boolean field 

Caused by: com.remondis.remap.MappingException: The method 'getNewsletterSubscribed' in type fr.monbanquet.magni.entity.CustomerEntity is not a valid Java Bean property get-method.

    private Boolean newsletterSubscribed;

    public Boolean getNewsletterSubscribed() {
        return newsletterSubscribed;
    }

    public void setNewsletterSubscribed(Boolean newsletterSubscribed) {
        this.newsletterSubscribed = newsletterSubscribed;
    }

And I use it like that 

            Mapping.from(CustomerEntity.class)
                    .to(SfContact.class)
                    .reassign(CustomerEntity::getMail).to(SfContact::getEmail)
                    .omitInSource(CustomerEntity::getNewsletterSubscribed) 
                    .mapper();

Regards

**Comment by schuettec** [comment]
Yes seems like a bug. I will have a look!

Thanks for your issue!

**Comment by mmaryo** [comment]
hope soon :)

**Comment by schuettec** [comment]
Fixed the bug. FYI:  https://github.com/remondis-it/remap/pull/36

**Comment by schuettec** [comment]
The fixed version is 3.0.4. I made a release. The synchronization with Maven Central is in progress.

Please let me know if the problem is solved for you. I will then close this issue.

**Comment by mmaryo** [comment]
with 3.0.4 I cannot import com.remondis.remap.Mapper
I wait for Maven Central sync

3.0.3 also

3.0.2 works

**Comment by schuettec** [comment]
This must be another problem. ReMap is available now through Maven Central in version 3.0.4: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.remondis%22%20AND%20a%3A%22remap%22

Version 3.0.3 does not exist. 

I migrated our projects successfully to ReMap 3.0.4.

**Comment by mmaryo** [comment]
it works very good now !
thanks a lot

**Comment by schuettec** [comment]
Great to hear. I will close this one. Thanks for reporting.
