### ISSUE TITLE
Supply parameters to mapper.map method

### ISSUE THREAD

**Issue by michalre** [remondis-it/remap#52]
My use case is:
Source:  Person with fields firstName, lastName, languageId
Destination: PersonDto with fields firstName, lastName, languageName

Can I somehow call mapper.map(person, languageNameByLanguageIdHashMap/producer of map) and define mapping for languageId -> languageName to get language name from this HashMap?

I can do it when creating mapping but I in my case, I create mapping when Spring starts and the HashMap needs to be created right before calling mapper.map( ) so that it contains latest data, because I am using it for something more dynamic than language.

**Comment by schuettec** [comment]
Yes you are reaching the limitations implied by the fact that ReMap was designed to convert objects field by field. Mixing more dynamic transformation/calculation aspects into the mapping changes the scope a little bit. 

Is it a valid workaround for you to build the mapper and it's configuration right before you want to use it? If yes, you could possibly solve your problem by using the replace operation.

**Comment by michalre** [comment]
Ok, makes sense, I think always recreating the mapper should not be a problem in my case.
