### ISSUE TITLE
Support for wrapping a mapper into a class

### ISSUE THREAD

**Issue by thombergs** [remondis-it/remap#58]
Currently, we're creating `Mapper` instances in Spring Java Configurations like this:

```java
@Configuration
public class MapperConfiguration {

  @Bean
  Mapper<MyClass1, MyClass2> myMapper() {
    return Mapping.from(...)
        // ...
        .mapper();
  }
}
```

We can then inject the mapper into other beans. However, this way, it's hard to find where the mapper is used within the codebase. I would have to search for "Mapper<MyClass1, MyClass2>" to find where it's injected.

It would be great if there was support for wrapping a Mapper into it's own class (or interface). It would look like this:

```java
@Configuration
public class MapperConfiguration {

  @Bean
  MyMapper myMapper() {
    return ...;
  }
}
```

In the IDE, we could then just search for occurrences of `MyMapper` to know where it's used.

It would be great if reMap supported "wrapper" classes  like `MyMapper` in the example above.

**Comment by schuettec** [comment]
Hi Tom,
to achieve this `com.remondis.remap.Mapper<S, D>` should become an interface. This way you can create those wrappers delegating to a real mapper instance. Maybe there is a nice way to support this with the API. 
But if you want those wrapper types you are creating classes for every mapping. This would likely pollute your classpath in greater projects wouldn't it?

**Comment by thombergs** [comment]
I'd trade better transparency in my codebase for a polluted classpath anytime :).

**Comment by schuettec** [comment]
Definitely. That's why I wrote a quick draft to get started with this. You may want to have a look at #59 just to make sure that we are talking about the same stuff :)
