### ISSUE TITLE
ClassNotFoundException: org.objectweb.asm.Type

### ISSUE THREAD

**Issue by mmaryo** [remondis-it/remap#60]
Hello 

I'm facing this error : ClassNotFoundException: org.objectweb.asm.Type

Need libraries update ?

**Comment by schuettec** [comment]
Yes we had similar issues when using dependencies that ship their own package of `org.objectweb` in an older version. Please checkout this paragraph from the Readme even though you are not using Spring Boot:

https://github.com/remondis-it/remap#spring-boot-issue

This could solve the issue - if you need further assistance let me know.
