### ISSUE TITLE
Reference to `this`

### ISSUE THREAD

**Issue by alfonz19** [remondis-it/remap#69]
Say that I have one input transfer object, and have to map it to class association, say jpa entities. These will be joined: there is 1 top level object, which has multiple child objects. Child objects has reference to top level object (currently not doable), and top level object will have reference to list of childs(current doable). We can do this by having mapping inside of mapping, but child cannot access toplevel object, because that one did call .mapper() yet. I'm not sure if I'm describing that in understandable manner, but mapping jpa entities association should be self descriptive.

**Comment by schuettec** [comment]
ReMap currently does not support cyclic references - it relies on independent transitive mappings.

For your usecase it may be easier to build the reference back to the top object only by setting the id. I know that JPA automatically maps references by id where possible. Please check if this is a suitable workaround for you.

We always try to avoid to map the whole objects. We cut down the mapping to id fields if we only need JPA to reference an entity.
