### ISSUE TITLE
How do I convert a List to Set?

### ISSUE THREAD

**Issue by shiruba** [remondis-it/remap#75]
I was trying out remap as a replacement for our mappers. The test by specification would be extremely useful to us.

My question is: We've got the case where we want to map a property of type `List<ADTO>` to a property of type `Set<A>`. Is this even supported?

I tried a combination of `replaceCollection` and `useMapper(TypeMapping.from(List.class).to(Set.class).applying(HashSet::new))` which results in the exception `com.remondis.remap.MappingException: Invoking access method for property...`.

**Comment by schuettec** [comment]
Hi thank you for reporting. From what you described I would say the Type Mapping seems to be the expected way to do what you try to accomplish. The `MappingException` is a bug i think.

A possible workaround is to use `replace` with a mapping function that converts the collection while calling the mapper explicitly.

Do you have a reproducing example that shows the exception? That might help to find a solution.

Thank you!

**Comment by schuettec** [comment]
Please checkout #76. Does this solve your issue?

**Comment by schuettec** [comment]
Merged. Target version 4.1.3.
