### ISSUE TITLE
Support for properties with capital letter on second place

### ISSUE THREAD

**Issue by buschmd** [remondis-it/remap#77]
The mapper creates property names from the get- or set-method transforming the first letter to lower case.

```
static String toPropertyName(Method method) {
    String name = method.getName();
    if (isBoolGetter(method)) {
      return firstCharacterToLowerCase(name.substring(2, name.length()));
    } else {
      if (isGetterOrSetter(method)) {
        return firstCharacterToLowerCase(name.substring(3, name.length()));
      } else {
        throw new IllegalArgumentException("The specified method is neither a getter nor a setter method.");
      }
    }
  }
```
  
In case of properties like 'aProp' with a getter 'getAProp' the PropertyDescripter does not convert the first character to lower case. The rule is no conversion, if the first two characters of the name are both uppercase.
So the mapper failed getting the PropertyDescripter because of no matching property name and the property will be marked as invalid java bean property.

```
  static PropertyDescriptor getPropertyDescriptorOrFail(Target target, Class<?> type, String propertyName) {
    Optional<PropertyDescriptor> property;
    property = Properties.getProperties(type, target)
        .stream()
        .filter(pd -> pd.getName()
            .equals(propertyName))
        .findFirst();
    if (property.isPresent()) {
      return property.get();
    } else {
      throw notAProperty(type, propertyName);
    }
  }
```

**Comment by schuettec** [comment]
Hi thanks for the issue. Sounds like a bug.

You wrote "The rule is no conversion, if the first two characters of the
name are both uppercase." Do you have a JavaDoc or something that states
this?

Thanks for your support ;-)

Am Do., 27. Dez. 2018, 15:39 hat Daniel Buschmann <notifications@github.com>
geschrieben:

**Comment by buschmd** [comment]
It's part of the JavaBean Specification. Here is the some extract:

> 8.8 Capitalization of inferred names.
> When we use design patterns to infer a property or event name, we need to decide what rules to follow for capitalizing the inferred name. If we extract the name from the middle of a normal mixedCase style Java name then the name will, by default, begin with a capital letter.
> Java programmers are accustomed to having normal identifiers start with lower case letters. Vigorous reviewer input has convinced us that we should follow this same conventional rule for property and event names.
> 
> Thus when we extract a property or event name from the middle of an existing Java name, we normally convert the first character to lower case. **However to support the occasional use of all upper-case names, we check if the first two characters of the name are both upper case and if so leave it alone.** 
So for example,
> “FooBah” becomes “fooBah” 
> “Z” becomes “z”
> “URL” becomes “URL”
> We provide a method Introspector.decapitalize which implements this conversion rule.

[https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/](url)

**Comment by schuettec** [comment]
Ah great thank you. Yep we should implement this.

Am Do., 27. Dez. 2018, 19:46 hat Daniel Buschmann <notifications@github.com>
geschrieben:

**Comment by schuettec** [comment]
I'm on it:
https://github.com/remondis-it/remap/pull/78

**Comment by schuettec** [comment]
Version 4.1.2 is on it's way to Maven Central and may be available in a few hours.

**Comment by buschmd** [comment]
Perfect, thanks for the quick implementation.
