### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by michalre** [remondis-it/remap#97]
Is it possible to tell mapper to throw an exception if some of the fields is not mentioned in mapping? I am using mapper to copy some fields between objects of the same class and want to detect when a new field is added to the class so that I can decide whether to omit it during copying or not.

**Comment by schuettec** [comment]
Do I understand it right: You would like to disable implicit field mappings to define the mappings for each field manually?

**Comment by michalre** [comment]
Yes exactly.

**Comment by schuettec** [comment]
No that's not possible with the current version. One would have to extend the API with a strict mode part where it is possible to define mappings that would normally be created implicitly.

**Comment by schuettec** [comment]
After having a thought on this I now think that it's not so complicated to add the feature you want. I imagine something like this:
```
Mapper<A, B> mapper = Mapping
    .from(A.class)
    .to(B.class)
    .noImplicitMappings()
    .reassign(A::getAField)
    .to(B::getAField)
```
We would just use reassign to declare the mappings that would be normally created as implicit mappings.

**Comment by michalre** [comment]
Yes, that would work for me.

**Comment by schuettec** [comment]
Seems like this feature is easy to implement. #98 is in pipe. Do you have the chance to compile and test the branch first? Just to double-check that I didn't miss anything.

**Comment by michalre** [comment]
I have tested it and it works as expected for my use case, thanks!
Btw I had to disable tests compilation, because of errors below but I am not sure if it is a problem in your build:

`
[ERROR] git/remap/src/test/java/com/remondis/remap/regression/typeMappingForCollectionsBug/MapperTest.java:[44,28] incompatible types: invalid method reference
    method getStrings in class com.remondis.remap.regression.typeMappingForCollectionsBug.A cannot be applied to given types
      required: no arguments
      found: java.lang.Object
      reason: actual and formal argument lists differ in length
[ERROR] /git/remap/src/test/java/com/remondis/remap/regression/typeMappingForCollectionsBug/MapperTest.java:[44,43] invalid method reference
  non-static method getStrings() cannot be referenced from a static context
[ERROR] /git/remap/src/test/java/com/remondis/remap/regression/typeMappingForCollectionsBug/MapperTest.java:[65,18] incompatible types: invalid method reference
    method getStrings in class com.remondis.remap.regression.typeMappingForCollectionsBug.A cannot be applied to given types
      required: no arguments
      found: java.lang.Object
      reason: actual and formal argument lists differ in length
[ERROR]/git/remap/src/test/java/com/remondis/remap/regression/typeMappingForCollectionsBug/MapperTest.java:[65,33] invalid method reference
  non-static method getStrings() cannot be referenced from a static context
`

**Comment by schuettec** [comment]
Okay perfect. The build failure appears if you run the build with JDK 8.
There is a compiler bug. The pipeline runs JDK 11 and the tests do not
crash.

I will try to do a release this weekend.

michalre <notifications@github.com> schrieb am Fr., 26. Apr. 2019, 17:22:

**Comment by schuettec** [comment]
FYI: ReMap 4.1.12 is on its way to Maven Central.

**Comment by michalre** [comment]
Perfect I will use it right away.
